return {
    getCopyIdKeyName = function()
        return "CopyIDToClipboard";
    end, 
    getConfigureKeyName = function()
        return "Configure";
    end, 
    getIsFriendOnlyKeyName = function()
        return "isFriendsOnly";
    end, 
    getIsActiveKeyName = function()
        return "isActive";
    end, 
    getIsForSaleKeyName = function()
        return "isForSale";
    end, 
    getVipServersIsEnabledKeyName = function()
        return "vipServersIsEnabled";
    end, 
    getEditKeyName = function()
        return "Edit";
    end, 
    getVersionHistoryKeyName = function()
        return "VersionHistory";
    end, 
    getOptInLocationsKeyName = function()
        return "OptInLocations";
    end, 
    getChinaKeyName = function()
        return "China";
    end, 
    getSelectedKeyName = function()
        return "selected";
    end, 
    getVoiceChatEnabledKeyName = function()
        return "VoiceChatEnabled";
    end, 
    getAvatarChatAudioEnabledKeyName = function()
        return "AvatarChatAudioEnabled";
    end, 
    getAvatarChatVideoEnabledKeyName = function()
        return "AvatarChatVideoEnabled";
    end, 
    getApprovedKeyName = function()
        return "Approved";
    end, 
    getInReviewKeyName = function()
        return "InReview";
    end, 
    getRejectedKeyName = function()
        return "Rejected";
    end, 
    getPlayerAcceptanceKeyName = function()
        return "PlayerAcceptance";
    end, 
    getGameSettingsKeyName = function()
        return "GameSettings";
    end, 
    getPluginKeyName = function()
        return "plugin";
    end, 
    getContextKeyName = function()
        return "context";
    end, 
    getLuobuStudioDevPublishKeyName = function()
        return "LuobuStudioDevPublish";
    end, 
    getTermsOfUseDialogKeyName = function()
        return "TermsOfUseDialog";
    end, 
    getCheckboxToggleKeyName = function()
        return "CheckboxToggle";
    end, 
    getButtonClickedKeyName = function()
        return "buttonClicked";
    end, 
    getFooterKeyName = function()
        return "Footer";
    end, 
    getScriptCollaborationEnabledOnServerKeyName = function()
        return "ScriptCollaborationEnabledOnServer";
    end, 
    getTeamCreateEnabledKeyName = function()
        return "TeamCreateEnabled";
    end
};
