return {
    White = Color3.fromRGB(255, 255, 255), 
    WorldProvider = {
        AdornedPartLimit = 200, 
        CameraMinMovementStepForPartUpdate = 50
    }, 
    WorldView = {
        BoxAdorn = {
            Size = Vector3.new(1.5, 1.5, 1.5), 
            Transparency = 0.3, 
            LineThickness = 0.03, 
            SurfaceTransparency = 0.7
        }, 
        OutlineAdorn = {
            Size = Vector3.new(1.5, 1.5, 1.5), 
            Transparency = 0.3, 
            LineThickness = 0.05
        }
    }
};
