return {
    BrickColor = require(script.BrickColorRenderer), 
    Color = require(script.ColorRenderer), 
    ColorSequence = require(script.SequenceRenderers.ColorSequenceRenderer), 
    Derive = require(script.DeriveRenderer), 
    FontFamily = require(script.FontRenderers.FontFamilyRenderer), 
    FontStyle = require(script.FontRenderers.FontStyleRenderer), 
    FontWeight = require(script.FontRenderers.FontWeightRenderer), 
    NumberSequence = require(script.SequenceRenderers.NumberSequenceRenderer), 
    PropertyName = require(script.PropertyNameRenderer), 
    StaticText = require(script.StaticTextRenderer), 
    Theme = require(script.BreadcrumbRadioRenderer), 
    TokenReference = require(script.TokenReferenceRenderer)
};
