return require(script:FindFirstAncestor("VisualizationModes").Packages.Framework).Styling.createStyleSheet("VisualizationModesDarkTheme", {}, {
    VisualizationModesHighlightColor = "$Blue70", 
    VisualizationModesHighlightTextColor = "$White", 
    VisualizationModesDivider = "$Gray110", 
    VisualizationModesDimActionHover = "$Gray80", 
    VisualizationModesBadgeBackground = "$Gray70", 
    VisualizationModesBadgeText = "$White"
});
