game:DefineFastFlag("UserInputPlaybackPluginShowMouseCursorAfterPlayback", false);
game:DefineFastFlag("UserInputPlaybackPluginDeferPackageLoading", false);
game:DefineFastFlag("UserInputPlaybackPluginFixRecordingFileSelectorNotUpdating", false);
game:DefineFastFlag("UserInputPlaybackPluginFixTabInitiallySelected", false);
game:DefineFastFlag("UserInputPlaybackPluginChooseRecordingNamePopUpFixStyle", false);
return nil;
