local _ = script.Parent.Parent.Parent;
return {
    "CampaignFilledNeutral", 
    "CheckFilledPositive", 
    "CreateFilledEmphasis", 
    "CreateFilledNeutral", 
    "CreateFilledWarning", 
    "EditOffFilledNegative", 
    "ErrorFilledError", 
    "HappyFilledNeutral", 
    "NotificationBell", 
    "NotificationSettings", 
    "PlayArrowFilledEmphasis", 
    "PlayArrowFilledNeutral", 
    "PlayArrowFilledWarning", 
    "PlayDisabledFilledNegative", 
    "ThreeDots", 
    "TranslateFilledNeutral", 
    "UpdateFilledEmphasis", 
    "UpdateFilledNegative", 
    "UpdateFilledPositive", 
    "UpdateFilledWarning", 
    "WarningFilledWarning"
};
