return {
    RESET_CAM_DARK = "rbxasset://textures/AssetImport/btn_dark_resetcam_28x28.png", 
    RESET_CAM_LIGHT = "rbxasset://textures/AssetImport/btn_light_resetcam_28x28.png", 
    PLAY_BUTTON = "rbxasset://textures/DeveloperFramework/MediaPlayerControls/play_button.png", 
    PAUSE_BUTTON = "rbxasset://textures/DeveloperFramework/MediaPlayerControls/pause_button.png", 
    LOADING_BUTTON = "rbxasset://textures/StudioSharedUI/pending.png"
};
